# Generated by Django 4.2.5 on 2023-10-02 19:38

from django.db import migrations, models
import gestao_pessoas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, validators=[gestao_pessoas.models.validate_full_name])),
                ('data_nascimento', models.DateField(validators=[gestao_pessoas.models.validar_data_nascimento])),
                ('endereco', models.CharField(max_length=200, validators=[gestao_pessoas.models.validate_address])),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viuvo', 'Viuvo')], max_length=10)),
            ],
        ),
    ]
